---
- name: Install Apache
  hosts: app
  become: true

  tasks:
    - name: Add an environment variable to the remote user's shell.
      lineinfile:
        dest: "~/.bash_profile"
        regexp: '^ENV_VAR='
        line: 'ENV_VALR=value'
      become: false
      #you can unbecome root in any task if you want
    - name: Get the value of an environment variable.
      shell: 'source ~/.bash_profile && echo $ENV_VAR'
      register: foo

    - debug: msg="The variable is {{ foo.stdout }}"

    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is running and starts at boot
      service:
        name: httpd
        state: started
        enabled: true
     
    - name: Copy test config file
      copy:
        src: files/test.conf
        dest: /etc/httpd/conf.d/test.conf
      notify:
        - restart apache
        - restart memcached

   handlers:
     - name: restart apache
       service:
         name: httpd
         state: restarted

     - name: restart memcahced
       state: restarted
