---
- name: Install apache
  hosts: all
  become: true
  tasks:
    #- name: Install Apache
    #  command: yum install --quiet -y httpd httpd-devel
    - name: Install Apache
      yum: 
        name:
          - httpd
          - httpd-devel
        state: present 
    - name: Copy configuration file
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest  }}"
        owner: root
        group: root
        mode: 0644
      with_items:
      - src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
          
     # - name: Copy configuration file
     # command: >
     #  cp httpd.conf /etc/httpd/conf/httpd.conf
     # - name: Start Apache and configure it to run at boot
     # command: service httpd start
     # - command: chkconfig httpd ony
    - name: Make sure Apache is started at boot
      service:
        name: httpd
        state: started
        enabled: true
